import type { MembershipPlan, Trainer, GymClass, Testimonial, FAQItem } from '@/types';

export const MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'basic',
    name: 'Basic',
    tagline: 'Start your journey',
    monthlyPrice: 49,
    yearlyPrice: 39,
    featured: false,
    color: '#6B6B6B',
    features: [
      'Full gym access (6am–10pm)',
      'Locker room & showers',
      'Free fitness assessment',
      '2 group classes/month',
      'Mobile app access',
      'Nutrition basics guide',
    ],
  },
  {
    id: 'standard',
    name: 'Standard',
    tagline: 'Most popular choice',
    monthlyPrice: 89,
    yearlyPrice: 69,
    featured: false,
    color: '#A0A0A0',
    features: [
      'Full gym access (24/7)',
      'Unlimited group classes',
      'Monthly trainer check-in',
      'Body composition analysis',
      'Nutrition coaching access',
      'Guest pass (2/month)',
      'Recovery zone access',
      'Priority class booking',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    tagline: 'The elite experience',
    monthlyPrice: 149,
    yearlyPrice: 119,
    featured: true,
    color: '#E5001A',
    features: [
      'Full gym access (24/7)',
      'Unlimited group classes',
      '4 personal training sessions/mo',
      'Custom meal plan',
      'Advanced body analytics',
      'VIP locker room',
      'Guest pass (unlimited)',
      'Priority booking – all facilities',
      'Recovery & spa access',
      'Quarterly transformation review',
    ],
  },
];

export const TRAINERS: Trainer[] = [
  {
    id: 't1',
    name: 'Marcus Webb',
    role: 'Head Strength Coach',
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=500&fit=crop&q=80',
    certifications: ['NSCA-CSCS', 'NASM-CPT', 'CrossFit L3'],
    specializations: ['Powerlifting', 'Athletic Performance', 'Body Recomposition'],
    experience: 12,
    clients: 340,
    instagram: '@marcuswebb_fit',
    bio: 'Former professional athlete turned elite strength coach. Marcus has trained Olympic competitors and Fortune 500 executives with equal dedication.',
  },
  {
    id: 't2',
    name: 'Daniela Cruz',
    role: 'CrossFit & HIIT Specialist',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=500&fit=crop&q=80',
    certifications: ['CrossFit L3', 'ACSM-CPT', 'Precision Nutrition L2'],
    specializations: ['CrossFit', 'HIIT', 'Metabolic Conditioning'],
    experience: 9,
    clients: 210,
    instagram: '@danielacruz_wod',
    bio: 'CrossFit Regional competitor and passionate coach. Daniela brings military-level discipline and infectious energy to every session.',
  },
  {
    id: 't3',
    name: 'James Okafor',
    role: 'Yoga & Mobility Expert',
    image: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&h=500&fit=crop&q=80',
    certifications: ['RYT-500', 'FMS Level 2', 'NASM-CES'],
    specializations: ['Yoga', 'Mobility', 'Injury Recovery', 'Mindfulness'],
    experience: 11,
    clients: 185,
    instagram: '@jamesokafor_yoga',
    bio: 'Blending ancient yoga wisdom with modern sports science, James helps athletes move better and recover faster. Trusted by pro athletes.',
  },
  {
    id: 't4',
    name: 'Sofia Reyes',
    role: 'Nutrition & Body Transformation',
    image: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=500&fit=crop&q=80',
    certifications: ['Precision Nutrition L2', 'ACE-CPT', 'ISSN Sport Nutrition'],
    specializations: ['Weight Loss', 'Muscle Gain', 'Contest Prep'],
    experience: 8,
    clients: 290,
    instagram: '@sofia_transforms',
    bio: 'Sofia\'s data-driven approach to nutrition and training has produced over 500 documented transformations. Results are her only language.',
  },
];

export const GYM_CLASSES: GymClass[] = [
  {
    id: 'c1',
    name: 'CrossFit WOD',
    instructor: 'Daniela Cruz',
    duration: 60,
    intensity: 'Extreme',
    category: 'CrossFit',
    description: 'High-intensity functional movements combining gymnastics, weightlifting, and metabolic conditioning for total athletic development.',
    icon: '⚡',
    color: '#E5001A',
    schedule: [
      { day: 'Mon', time: '6:00 AM' },
      { day: 'Wed', time: '6:00 AM' },
      { day: 'Fri', time: '6:00 AM' },
      { day: 'Sat', time: '8:00 AM' },
    ],
  },
  {
    id: 'c2',
    name: 'Strength & Power',
    instructor: 'Marcus Webb',
    duration: 75,
    intensity: 'High',
    category: 'Strength',
    description: 'Periodized barbell and compound movement training designed to maximize strength gains and build lean muscle mass systematically.',
    icon: '🏋️',
    color: '#FF6B00',
    schedule: [
      { day: 'Tue', time: '7:00 AM' },
      { day: 'Thu', time: '7:00 AM' },
      { day: 'Sat', time: '10:00 AM' },
    ],
  },
  {
    id: 'c3',
    name: 'HIIT Cardio Burn',
    instructor: 'Daniela Cruz',
    duration: 45,
    intensity: 'High',
    category: 'Cardio',
    description: 'Interval-based cardiovascular training that torches calories, boosts metabolism, and improves endurance in half the time.',
    icon: '🔥',
    color: '#E5001A',
    schedule: [
      { day: 'Mon', time: '12:00 PM' },
      { day: 'Wed', time: '12:00 PM' },
      { day: 'Fri', time: '5:30 PM' },
    ],
  },
  {
    id: 'c4',
    name: 'Power Yoga Flow',
    instructor: 'James Okafor',
    duration: 60,
    intensity: 'Medium',
    category: 'Yoga',
    description: 'Dynamic yoga linking breath with movement. Builds functional flexibility, core stability, and mental resilience for athletes.',
    icon: '🧘',
    color: '#7C3AED',
    schedule: [
      { day: 'Tue', time: '6:30 AM' },
      { day: 'Thu', time: '6:30 AM' },
      { day: 'Sun', time: '9:00 AM' },
    ],
  },
  {
    id: 'c5',
    name: 'Personal Training',
    instructor: 'All Trainers',
    duration: 60,
    intensity: 'High',
    category: 'Personal',
    description: '1-on-1 custom sessions fully tailored to your goals, fitness level, and schedule. Maximum results guaranteed.',
    icon: '🎯',
    color: '#059669',
    schedule: [
      { day: 'Mon–Sat', time: 'By Appointment' },
    ],
  },
  {
    id: 'c6',
    name: 'Body Sculpt',
    instructor: 'Sofia Reyes',
    duration: 50,
    intensity: 'Medium',
    category: 'Cardio',
    description: 'Sculpt and tone every muscle group with resistance training and high-rep circuits. Perfect for body recomposition goals.',
    icon: '💪',
    color: '#DB2777',
    schedule: [
      { day: 'Mon', time: '7:00 PM' },
      { day: 'Wed', time: '7:00 PM' },
      { day: 'Fri', time: '7:00 PM' },
    ],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'r1',
    name: 'Alex Thompson',
    role: 'Software Engineer',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: 'DragFit changed my life completely. In 6 months I lost 42 lbs and built more muscle than I ever had in years of casual gym-going. The trainers here are on another level.',
    transformation: '-42 lbs / +18 lbs muscle',
    months: 6,
  },
  {
    id: 'r2',
    name: 'Maria Santos',
    role: 'Marketing Director',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: 'After two kids, I thought my body was just "done." DragFit proved me completely wrong. Sofia\'s nutrition plan and the CrossFit classes gave me the best body of my life at 38.',
    transformation: 'Post-pregnancy transformation',
    months: 8,
  },
  {
    id: 'r3',
    name: 'Jordan Williams',
    role: 'Professional Athlete',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: 'As a professional, I\'ve trained at elite facilities worldwide. DragFit stands with the best I\'ve ever experienced. Marcus Webb is genuinely one of the top strength coaches alive.',
    transformation: '+31 lbs lean mass in 10 months',
    months: 10,
  },
  {
    id: 'r4',
    name: 'Priya Mehta',
    role: 'Entrepreneur',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: 'The 24/7 access was the selling point. But the community kept me here. I went from barely walking up stairs to completing my first half marathon. Unreal progress.',
    transformation: 'Completed first half-marathon',
    months: 5,
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: 'f1',
    question: 'Do you offer a free trial?',
    answer: 'Yes! We offer a free 7-day trial for all new members. You\'ll have full access to all facilities, group classes, and a complimentary fitness assessment with one of our expert trainers. No credit card required to start.',
    category: 'Membership',
  },
  {
    id: 'f2',
    question: 'What are your gym hours?',
    answer: 'Premium and Standard members enjoy 24/7 gym access. Basic members have access from 6am to 10pm daily. Staffed hours are Monday–Friday 5am–11pm and Saturday–Sunday 6am–10pm.',
    category: 'Facilities',
  },
  {
    id: 'f3',
    question: 'Can I freeze or cancel my membership?',
    answer: 'Absolutely. You can freeze your membership for up to 3 months per year (medical or travel reasons) with no fees. Month-to-month memberships can be cancelled with 30 days notice. Annual plans can be cancelled with a prorated refund.',
    category: 'Membership',
  },
  {
    id: 'f4',
    question: 'Do I need experience to join?',
    answer: 'Not at all. We welcome everyone from complete beginners to elite athletes. Every new member receives a complimentary fitness assessment and orientation session to ensure you start safely and confidently.',
    category: 'Getting Started',
  },
  {
    id: 'f5',
    question: 'What equipment do you have?',
    answer: 'Our facility features over 200 pieces of premium equipment: full power rack arrays, Olympic platforms, cable systems, cardio theatre, functional training rigs, turf track, and a full CrossFit box. Everything is commercial grade and maintained daily.',
    category: 'Facilities',
  },
  {
    id: 'f6',
    question: 'Are personal training sessions included?',
    answer: 'Personal training sessions are included in our Premium plan (4 sessions/month). Standard and Basic members can purchase PT sessions individually or in packages at preferential member rates starting at $65/session.',
    category: 'Training',
  },
  {
    id: 'f7',
    question: 'Do you have parking?',
    answer: 'Yes, we offer free dedicated parking for 150+ vehicles available 24/7. We also have secure bicycle storage and are located 2 minutes from the Metro station.',
    category: 'Facilities',
  },
  {
    id: 'f8',
    question: 'Is there a nutritionist on staff?',
    answer: 'Yes. Our certified nutrition coaches (including our Precision Nutrition Level 2 certified specialists) are available for consultations. Premium members receive full nutrition coaching. All members can book nutrition consults separately.',
    category: 'Nutrition',
  },
];

export const STATS = [
  { label: 'Active Members', value: 3800, suffix: '+' },
  { label: 'Expert Trainers', value: 24, suffix: '' },
  { label: 'Classes Weekly', value: 180, suffix: '+' },
  { label: 'Transformations', value: 5200, suffix: '+' },
];

export const FACILITIES = [
  { name: 'Olympic Lifting Platforms', count: 8, icon: '🏋️' },
  { name: 'Power Racks', count: 16, icon: '💪' },
  { name: 'Cardio Theatre Machines', count: 40, icon: '🏃' },
  { name: 'CrossFit Box', count: 1, icon: '⚡' },
  { name: 'Functional Training Rig', count: 2, icon: '🔄' },
  { name: 'Recovery & Spa Area', count: 1, icon: '🧖' },
  { name: 'Turf Track (40m)', count: 1, icon: '🏟️' },
  { name: 'Yoga & Mindfulness Studio', count: 2, icon: '🧘' },
];
